ALTER TABLE creatures ALTER COLUMN creature_class TYPE VARCHAR(80), ALTER COLUMN creature_class SET NOT NULL;
ALTER TABLE creatures ALTER COLUMN "level" TYPE INT, ALTER COLUMN "level" SET NOT NULL, ALTER COLUMN "level" DROP DEFAULT;
ALTER TABLE creatures ALTER COLUMN xp TYPE INT, ALTER COLUMN xp SET NOT NULL, ALTER COLUMN xp DROP DEFAULT;
ALTER TABLE creatures ALTER COLUMN hp TYPE INT, ALTER COLUMN hp SET NOT NULL, ALTER COLUMN hp DROP DEFAULT;
ALTER TABLE creatures ALTER COLUMN speed TYPE INT, ALTER COLUMN speed SET NOT NULL, ALTER COLUMN speed DROP DEFAULT;
ALTER TABLE creatures ALTER COLUMN attack TYPE INT, ALTER COLUMN attack SET NOT NULL, ALTER COLUMN attack DROP DEFAULT;
