ALTER TABLE player_creatures ALTER COLUMN creature_class TYPE VARCHAR(80), ALTER COLUMN creature_class SET NOT NULL;
ALTER TABLE player_creatures ALTER COLUMN "level" TYPE INT, ALTER COLUMN "level" SET NOT NULL, ALTER COLUMN "level" DROP DEFAULT;
ALTER TABLE player_creatures ALTER COLUMN xp TYPE INT, ALTER COLUMN xp SET NOT NULL, ALTER COLUMN xp DROP DEFAULT;
ALTER TABLE player_creatures ALTER COLUMN hp TYPE INT, ALTER COLUMN hp SET NOT NULL, ALTER COLUMN hp DROP DEFAULT;
ALTER TABLE player_creatures ALTER COLUMN speed TYPE INT, ALTER COLUMN speed SET NOT NULL, ALTER COLUMN speed DROP DEFAULT;
ALTER TABLE player_creatures ALTER COLUMN attack TYPE INT, ALTER COLUMN attack SET NOT NULL, ALTER COLUMN attack DROP DEFAULT;
ALTER TABLE player_creatures ADD PRIMARY KEY (id);
ALTER TABLE IF EXISTS player_creatures DROP CONSTRAINT IF EXISTS indx_player_creatures_id;
DROP INDEX IF EXISTS indx_player_creatures_id_player;
