ALTER TABLE combats ALTER COLUMN started_at TYPE VARCHAR(20), ALTER COLUMN started_at SET NOT NULL, ALTER COLUMN started_at DROP DEFAULT;
ALTER TABLE combats ALTER COLUMN updated_at TYPE VARCHAR(20), ALTER COLUMN updated_at SET NOT NULL, ALTER COLUMN updated_at DROP DEFAULT;
DROP INDEX IF EXISTS indx_combats_id_player1;
DROP INDEX IF EXISTS indx_combats_id_player2;
